### ISSUE TITLE
GPL-559	Automatically batch lighthouse sentinel samples

### ISSUE THREAD

**Issue by rl15** [sanger/lighthouse-ui#10]
**User story**
GPL-559 | As genomics POs (Emma, Rich C & James) we would like Lighthouse sentinel samples to be automatically batched for cherry picking

**Who are the primary contacts for this story**
Emma G
Rich C
James M
Danni W

**Acceptance criteria*
To be considered successful the solution must allow:
- [ ] Extend GUI delivered in GPL-558 to allow selection and deselection of plates (and so the samples on the plate) - see mockup
- [ ] Indicate with feedback that plate has been removed from a batch*1
- [ ] Create cherry pick batch in sequencescape from selected plates
- [ ] feedback to user batch number when successfully created. 

*1 There maybe a better way to feedback that a plate and so its samples have been excluded from the mega batch than a table underneath (EG big red cross next to item /greyed out?). However this is working design for now.  

**Dependencies**
This story has dependency on GPL-558: https://github.com/sanger/lighthouse-ui/issues/2 
And:
https://github.com/sanger/sequencescape/issues/2837

**Additional context**
See sequence flow diagram: https://ssg-confluence.internal.sanger.ac.uk/x/jqsKBg

**Comment by stevieing** [comment]
Tasks
* create a new endpoint in Labwhere to retrieve labwares for multiple locations
* create a new page in lighthouse ui to create a mega cherrypicking batch from multiple box barcodes
* create an api request in the lighthouse ui to create mega batch in sequencescape
* update the process flow diagram in confluence to add the sentinel batch create and cherrypicking

**Comment by stevieing** [comment]
Sequencescape endpoint:

```
{
          'data' => {
            'type' => 'pick_lists',
            'attributes' => {
              'asynchronous' => true,
              'labware_pick_attributes' => [
                { source_labware_id: plate_1.id },
                { source_labware_barcode: plate_2.machine_barcode },
              ]
            }
          }
        }
```
