### ISSUE TITLE
DPL-180 [BUG] - When a user visits the page via https they get a network error as lighthouse is http only (S=S, V=4)

### ISSUE THREAD

**Issue by stevieing** [sanger/lighthouse-ui#139]
**Describe the bug**
When a user visits the page via https they get a network error as lighthouse is http only. This causes issues in the lab as they are unable to access the results in Boxbuster.

Until https is fully implemented we need to ensure that lighthouse-ui is directed to http.

**RT Ticket Number**
#738242

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by emrojo** [comment]
This was the original ticket to solve the problem, it was created a while ago:

https://github.com/sanger/lighthouse-ui/issues/27
