### ISSUE TITLE
GPL-558 Scan Lighthouse BOX barcode and generate sample in SS for sentinel

### ISSUE THREAD

**Issue by rl15** [sanger/lighthouse-ui#2]
**User story**
GPL-558 | As genomics POs (Emma, Rich C & James) we would like Lighthouse sentinel samples to be automatically created in sequencescape by scanning a BOX barcode to support a 5 day turn-around-time

**Who are the primary contacts for this story**
Emma G
Rich C
James M
Danni W

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Mock up of GUI agreed with Danni to 
- [x] Scan in a Lighthouse BOX barcode
- [x] Request the plate barcodes in to box from LabWhere (assumes box manifest has been uploaded previously see GPL-468)
- [x] Request plate map metadata, root sample id, result (+ve, -ve or void)
- [x] Request COG-UK id with correct prefix dependent on Lighthouse Lab (MILK, ALDP ...) (in barcoda - is a message where you give the prefix and baracoda gives you back a barcode per sample. the barcode identifies each sample we received in lighthouse, so a plate would request 96 barcodes and is applied to each sample)
- [x] Create  (Just +ves?) sample in SS, including entery to stock_resourse table in MLWH (See GPL-577)
- [ ] Report back number plates, and samples created and if box barcode unknown, any plate barcodes unknown 

Update:
- Request to labwhere, with box barcode, returns a list of plate barcodes
- for each plate barcode, request to lighthouse to do belo
- create new endpoint in lighthouse to accept a plate barcode, to create a plate in SS, with only the possitive samples (where Result=True)
- For each plate created, (from the above requst) return a list of the plates positive samples (RootSampleID), including an error for any plate that failed to be created
- Lighthouse UI display list of plates and number of +ve samples created in SS (from lighthouse /plates/new <updated> request)

- mocking out the request to lighthouse 
- response =  [{plateBarcode: 1, numOfPosSamplesCreates: 2}, {plateBarcode: 2, numOfPosSamplesCreates: 2}] }

**Additional context**
See sequence flow diagram: https://ssg-confluence.internal.sanger.ac.uk/x/jqsKBg  
Current process in Asset Audits is too slow
Adding to Crawler to put all Lighthouse related work in one service to aid maintainability

**Comment by harrietc52** [comment]
Todo (after quick test in UAT):
- [ ] Reload table on response
- [ ] Check SS response in lighthouse, and return better error message
- [ ] Include plate barcode in error message

**Comment by stevieing** [comment]
Labwhere - for testing to ensure that the plates exist in labwhere. In UAT Labwhere scan the plates into the box. Go to the home page, scan the box barcode into the location box. Scan the barcodes of all of the relevant plates into the labwares box.

**Comment by harrietc52** [comment]
Lighthouse - Get the plate barcode for positive samples: http://uat.lighthouse.psd.sanger.ac.uk/samples?where{Result:True}

**Comment by stevieing** [comment]
To get the positive samples for lighthouse:
http://lighthouse/samples?where{Result:True}
