### ISSUE TITLE
DPL-316 [Research] Heron - Failed cherrypick destination plates have not been recorded [C=?, v=?]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/lighthouse-ui#220]
**Description**
As Carl R (GSU/CoTrack), Sara S (Ops) and Scott T (R&D) we would like to understand if failed cherrypick destination plates (ones not progressed into library prep) can be identified, and whether the barcodes then could be used to generate timestamp appropriate failed plate events in the LIMS and MLWH so that reporting on failed samples becomes possible.

**Who the primary contacts are for this work**
Carl R
Sara S
Scott T

**Knowledge or Stake holders**
Andrew S
Eduardo MR

**Acceptance Criteria**
a) find out if we can identify such plates for both Beckman and Biosero routes, with care to check that samples within all such plates are not in Sequencescape (in case picked later in secondary attempts)
b) consider how we can create the fail plate events with appropriate timestamps for these plate barcodes
c) agree with GSU/CoTrack which timestamp is appropriate to use in the case there is more than one option

**Additional context or information**
Carl needs to identify those samples that failed during the cherrypicking step in the Heron pipeline.

There is no automatic failure of destination plates (and their samples) in the robotic methods as there is too much variety in what can go wrong and they will attempt to save the plates where possible. Instead there are screens within the Lighthouse-UI application for Beckman and Biosero that the user scans the plate barcode into to 'fail' it. 

This creates either an 'lh_biosero_cp_destination_plate_failed' event for Biosero or 'lh_beckman_cp_destination_failed' event for Beckman in MLWH events, and the event includes the list of samples contained within the plate. The event contents can then be queried in reporting.

Unfortunately the lab has not been using these screens and their use is not part of current SOPs/training.
Sara S is working on implementing this now.

This leaves legacy failed plates and samples. Its should be possible to compare the lists of destination plates created in either Cherrytrack (Biosero) or DART (Beckman) databases, against created plates in LIMS (Sequencescape) to identify those that never made it to cherrypicking. Then generate the appropriately dated failed plate events for those barcodes.

**Comment by sdjmchattie** [comment]
Looking first at Biosero events, the following SQL run on the Cherrytrack database shows 47 destination plates that may have been aborted pre-maturely.  I now need to check these in Sequencescape to see whether any of the samples on these plates have since been picked and therefore the plate should not be marked as failed.

`SELECT
	DISTINCT(destination_plate_wells.barcode)
FROM
	automation_system_runs
INNER JOIN destination_plate_wells
	ON automation_system_runs.id = destination_plate_wells.automation_system_run_id
INNER JOIN source_plate_wells
	ON destination_plate_wells.source_plate_well_id = source_plate_wells.id
WHERE
	automation_system_runs.state != "completed";`

**Comment by sdjmchattie** [comment]
The merge request for this research story is here: https://gitlab.internal.sanger.ac.uk/psd/data-patch-archive/-/merge_requests/5

**Comment by sdjmchattie** [comment]
The completed research is documented in the GitLab repository at https://gitlab.internal.sanger.ac.uk/psd/data-patch-archive/-/tree/main/patches/2022/0824-dpl-316-create-failed-plate-events

This has been exported as a PDF and sent to the primary contacts, including Cristina A.
