### ISSUE TITLE
GPL-828-1 Refactor Print Label child pages

### ISSUE THREAD

**Issue by harrietc52** [sanger/lighthouse-ui#46]
Below thoughts from [PR](https://github.com/sanger/lighthouse-ui/pull/43)

One way to refactor, as the Destination Plate/ Ad Hoc/ Control Plate/ Source Plate/Reagent Aliquots pages are all quite similar, could be having a Print Label page as a template for all these pages, then using slots, the duplication could hopefully be reduced.

_--- or ---_

We think the 5 print label pages are similar enough to have in one component, with some logic/ config determining the differences. That would remove the need to refactor out the status/ printer component/ navbar etc
Refactor use of Alert too.

**Update for 10th November 2022**

After adding a fifth label printing page in [a PR](https://github.com/sanger/lighthouse-ui/pull/418) for [GPL-905](https://github.com/sanger/lighthouse-ui/issues/54), it became clear that there are number of TODOs in the label printing pages.  At the time of writing, these are as follows with suggestions for how to fix them:

- TODOs shared across all the label pages
  - [x] [Create a component to show the status of the page](https://github.com/sanger/lighthouse-ui/blob/develop/pages/print_labels/ad_hoc_plate.vue#L9) -- could use some of the logic of AlertDialog to create a common component for statuses.
  - [x] [Generate methods for statuses dynamically](https://github.com/sanger/lighthouse-ui/blob/develop/pages/print_labels/ad_hoc_plate.vue#L80) -- by passing the status value directly to a new component as above, these methods wouldn't need to exist here.
  - [x] [Deduplicate tests for statuses](https://github.com/sanger/lighthouse-ui/blob/develop/test/pages/print_labels/ad_hoc_plate.spec.js#L62) -- these tests can be applied to the new component for displaying status messages instead of in the label printing page.
- While the above are being fixed, we should also see if we can deal with the remaining two TODOs for source label unit tests:
  - [x] [Refactor three arbitrary tests](https://github.com/sanger/lighthouse-ui/blob/develop/test/pages/print_labels/source_labels.spec.js#L54) -- investigate why these are arbitrary.  I think they are just to check that no errors are thrown, but they could be to stop the code coverage checker complaining without actually performing any tests.  If it's the former, Jest should be used to check that no error is thrown by [expecting it not to throw](https://stackoverflow.com/a/49603347).
  - [x] [Stop using console.log for confirming that code doesn't throw](https://github.com/sanger/lighthouse-ui/blob/develop/test/pages/print_labels/source_labels.spec.js#L75) -- this becomes redundant when using the proper Jest syntax as above.

**Comment by sdjmchattie** [comment]
I've emailed Rory and Adam to see whether the printers are still working as they used to after the refactor and updates.

**Comment by sdjmchattie** [comment]
This was tested by Avi and is working as expected.
