### ISSUE TITLE
GPL-843 Flag 'Must sequence' and 'preferentially sequence' samples in box buster

### ISSUE THREAD

**Issue by rl15** [sanger/lighthouse-ui#51]
**User story**
GPL-843 | As core LIMS we would like to enhance Boxbuster GUI to notify to operations a plate contains important samples, must sequence or preferentially sequence and it should be cherry picked preferentially

NB 
Must sequence - Business rules on Result, Controls, or CT values are ignored 
Preferentially Sequence - Flag as 'fit to pick' only if pass business rules

**Who are the primary contacts for this story**
Callum S (PAM)
Ryes (PAM)
Harry C
Philip VV
Eduardo MR

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Show to operations via box buster (See mock up link below)
- [ ] Samples that must be sequenced, These are samples flagged True by PAM that must be sequenced regardless of probability will produce good sequence (Eg Sample bypass business rules on Result, If control or Ct values)  
- [ ] Samples that should be sequenced preferentially, These are samples flagged as True by PAM that *also* then  pass business rules on Result, Control and Ct filters

NB We are expecting preferentially sequence to be te most used field by PAM to prioritize samples. 

**Additional context**
See mock up: https://lucid.app/lucidchart/invitations/accept/af2a4c65-1a9a-498e-a77c-3dcc2e774e8f

**Comment by harrietc52** [comment]
09/02/21 - messaged Rich C asking to confirm whether sortable fields are required in Box Buster, as well as the default sorting

**Comment by rl15** [comment]
Callum S (PAM) wrote (Wednesday, 24 February 2021 at 21:24)

'the box buster alterations suppressed for the time being (toggle off the GUI change when deploy to production)'

but retain all of other 'Important samples functuon - Rich L
