### ISSUE TITLE
GPL-969 UAT Action - Setup Cherrypick Test Data UI [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/lighthouse-ui#73]
**User story**
As a dev team or R&D team we would like an interface in the lighthouse UI which we can use to create the SAT data and/or files.

This should query the lighthouse API endpoints to populate mongo with the UAT testing data.

**Who are the primary contacts for this story**
Philip
Andrew

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] A new tab exists calls **UAT Actions**
- [ ] UAT Actions tab contains a page where users can create **Setup Cherrypick Test Data**. This page should allow a user to enter a number of plates, specifying how many positives should be on that plate. There should also be a check box requesting whether the Cherrypick Test Data should be added to DART or not. 
- [ ] On clicking "Generate Cherrypick Test Data":
- [ ] Lighthouse UI should send a POST request to Lighthouse `/test-run-data`, with the information for a test run. Including number of plates, number of positives, addToDart flag. 
- [ ] Lighthouse accepts POST request and stubs out implementation ([GPL-967 ](https://github.com/sanger/lighthouse/issues/322)covers implementation). A 201 is returned if Lighthouse successfully generates plate barcodes from Baracoda, and creates the test-run-data in Mongo. Otherwise a 400 is returned. 
- [ ] If a 400 is returned, user should be informed. 
- [ ] If a 201 is returned, the id of the run-test-data is also returned and user should be taken to a "Summary" page for this run test data ID
- [ ] A Polling page is created where the Lighthouse UI polls the Lighthouse service every 5 seconds, to GET /test-run/{id}&_include=status . Stay on this page until the included status is "Completed". Should this page be exitable? Whats the page of this page, if a user wanted to revisit it later?
- [ ] When the polling of the tun test data status returns completed, the user should be taken to the Summary page of the Test Run Data. 
- [ ] A Summary page is created for the Test Run Data id. This shows a table with the Test Runs plates, and the number of positive barcodes on the plate.  
- [ ] The Summary page has a drop down to select with printer to use
- [ ] For each Plate, there is a button to print the labels for the plate.
- [ ] There is a Print all labels button 
- [ ] On Printing, a request is send from Lighthouse UI to SPrint

**Dependencies**
This story is blocked by the following dependencies:
https://github.com/sanger/lighthouse/issues/322

**Additional context**
LucidChart diagram [here](https://lucid.app/lucidchart/invitations/accept/inv_1b8208a2-17e8-498d-a301-bf34b64f3c6d) showing Lighthouse UI mock ups and UAT Action process

**Comment by harrietc52** [comment]
LucidChart diagram [here](https://lucid.app/lucidchart/invitations/accept/inv_1b8208a2-17e8-498d-a301-bf34b64f3c6d) showing Lighthouse UI mock ups and UAT Action process
