### ISSUE TITLE
DPL-031 Supressing Changes to Production Box Buster for Algorithm Prioritisation [#721609]

### ISSUE THREAD

**Issue by rl15** [sanger/lighthouse-ui#82]
**Description**
Select option below (and or generate further options or provide better detail on option 1) 
Do the work.

**Who the primary contacts are for this work**
Callum S
Philip VV
Eduard MR
James M (Ops)

**Options**

1. Test this in UAT (issue with MongoDb UUIDS)
2. Inform operation to ignore fields for test (NB I have heard back that the heron_sulston at sanger.ac.uk email alias will capture all the lab staff - James M Thursday, 3 June 2021 at 16:12)
3. Revert Changes to Production Box Buster GUI (flags will still be set in MLWH and impact on Beckman picks unless plates are never placed on Beckmans)

**Additional context or information**
Callum wrote (Tue, 1 Jun 2021 12:04:17 +0000) See: https://rt.sanger.ac.uk/Ticket/Display.html?id=721609

A few months ago changes were made to box buster which would display the sum of the “Must sequence” and “Preferentially sequence” flags in MLWH which was to aid sample prioritisation through an algorithm we had developed.  This was supposed to be supressed in production but Rich Livett has informed me that the fields are visible:

We are now in a position to begin testing the algorithm in production and to prevent operational confusion we need to have this information supressed.  I am not sure if the above captures all changes that were made to box buster to support this work but if there are any others they will also need to be supressed.  Once we have carried out full testing we can then have it turned back on.

See backlog items of original work

https://github.com/sanger/lighthouse/issues/247
https://github.com/sanger/lighthouse-ui/issues/51
https://github.com/sanger/crawler/issues/256
https://github.com/sanger/unified_warehouse/issues/172

NB These is a note on the done swim lane: 
Toggle on 'Important samples GUI  <and?>' 
in UAT for 6th April [Enable Tuesday morning]

**Comment by stevieing** [comment]
Algorithm is now in production
