### ISSUE TITLE
DPL-081-3 Create a drop down for selection of control plates (C=S, V=3)

### ISSUE THREAD

**Issue by sdjmchattie** [sanger/lighthouse-ui#97]
**User story**
As a user of SequenceScape, I want to be able to choose which control plate barcode I can print a label for using a drop down.

**Who are the primary contacts for this story**
Stuart McHattie

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] When printing labels for a control plate barcode, the option to enter the barcode for the control plate should be a preset list of options containing the two available control plates for Heron.

References
This story has a non-blocking relationship with:
- https://github.com/sanger/sequencescape/issues/3272

**Additional context**
The values in the drop down can be hard coded for now since the control plates are rarely modified.  If we need a free text entry again, this can be done later by adding an "Other" option or making the box be a combo text entry + drop down with filtering.

![image](https://user-images.githubusercontent.com/1999241/128485180-b07390d5-a6d4-46a5-9528-91e9b66545c1.png)

**Comment by stevieing** [comment]
Check with Scott Thurston as to whether this is still relevant.

**Comment by stevieing** [comment]
From Scott (27/01) 

- at the moment they are appear to be free to type in any alphanumeric sequence. This was discovered by Tiago in the Heron team, when he noticed some nonsense control barcodes during troubleshooting
- The team had been relying on suggestions from the  box (cache/cookies) to suggest the right numbers, when there were options that looked vaguely similar to the right barcode, mis-selections started occurring.
- We cleared the cache and put in the 2 correct barcodes, but it’s only a matter of time before it happens again

**Comment by sdjmchattie** [comment]
I have spoken to Scott and he agrees that this is no longer a concern as the strip tubes have eliminated the issue.
